apiVersion: v1
kind: Service
metadata:
  labels:
    app: station
  name: station
spec:
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30111
  selector:
    app: station
  type: NodePort