apiVersion: v1
kind: Service
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30111
  selector:
    app: workspace
  type: NodePort