apiVersion: v1
kind: Pod
metadata:
  name: workspace
  labels:
    app: workspace
spec:
  containers:
    - name: workspace
      image: amanhobo/workspace:latest
      ports:
        - containerPort: 22
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - AUDIT_CONTROL
            - AUDIT_WRITE
      env:
        - name: USERNAME
          value: username
        - name: PASSWORD
          value: password
